spring:
  datasource:
    url: jdbc:h2:mem:property_test_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql
